SCREEN_WIDTH, SCREEN_HEIGHT = 1080, 720

GAME_TITLE = "Digimon World Remake"

FONT_SIZE = 74
FONT_TYPE = None

MENU_OPTIONS = ["New Game", "Continue Game"]

FPS = 60

PLAYER_NAME = ""
PARTNER_NAME = ""
